.\" Manpage for memwatch
.TH MEMWATCH 1 "MAY 2015" Linux "User Manuals"
.SH NAME
memwatch \- show memory usage statistics in real-time
.SH SYNOPSIS
memwatch [options]
.SH DESCRIPTION
This programm reads /proc/meminfo and prints memory and swap statistics.
.SH OPTIONS
.TP
\fB\-h\fR
Prints help message
.TP
\fB-d\fR \fImiliseconds\fR
Set refresh timeout in miliseconds. Minimum value is 100(0.1s), maximum is 100000(100s).
.SH AUTHOR
Pavel Balaev (pascal@unixdev.ru)
