.\" Manpage for memwatch
.TH MEMWATCH 1 "APR 2016" Linux "User Manuals"
.SH NAME
memwatch \- Shows memory usage statistics in real time.
.SH SYNOPSIS
memwatch [options]
.SH DESCRIPTION
This program reads /proc/meminfo and prints memory and swap statistics.
.SH OPTIONS
.TP
\fB\-h\fR
Prints help message.
.TP
\fB-d\fR \fIseconds\fR
Set data update time in seconds. Minimum value is 0.1, maximum is 100.
.TP
\fB\-v\fR
Prints version.
.SH INTERACTIVE COMMANDS
.LP
The following commands are supported while in memwatch:
.LP
.TP
.B q
Exit memwatch.
.TP
.B b
Display the amount of memory in bytes.
.TP
.B k
Display the amount of memory in kilobytes.
.TP
.B m
Display the amount of memory in megabytes.
.SH AUTHOR
Pavel Balaev (pascal@unixdev.ru)
