.\" Manpage for memwatch
.TH MEMWATCH 1 "MAY 2016" Linux "User Manuals"
.SH NAME
memwatch \- Shows memory usage statistics in real time.
.SH SYNOPSIS
.B memwatch
.RI [ options ]
.SH DESCRIPTION
This program reads /proc/meminfo and prints memory and swap statistics.
.TP
The displayed keys for physical ram (Memory [unit size]):
.TP
\fBTotal\fR
Total usable ram.
.TP
\fBFree\fR
Unused memory.
.TP
\fBUsed\fR
Used memory (calculated as Total - Free - Buff - Cache).
.TP
\fBBuff\fR
Memory used by kernel buffers.
.TP
\fBCache\fR
Memory used by the page cache and slabs.
.TP
\fBAvail\fR
An estimate of how much memory is available for starting new applications, without swapping.
.TP
The displayed keys for swap (Swap [unit size]):
.TP
\fBTotal\fR
Total amount of swap space available.
.TP
\fBFree\fR
Unused swap space.
.TP
\fBUsed\fR
Used swap space.
.SH OPTIONS
.TP
\fB-d\fR, \fB\-\-delay\fR \fIseconds\fR
Set data update interval. Minimum value is 0.1, maximum is 60.
.TP
\fB-S\fR, \fB\-\-si\fR
Print sizes in powers of 1000 instead of 1024. In the International System of Units (SI) the prefix kilo means 1000.
.TP
\fB\-b\fR, \fB\-\-bytes\fR
Display the amount of memory in bytes.
.TP
\fB\-k\fR, \fB\-\-kilo\fR
Display the amount of memory in kilobytes.
.TP
\fB\-m\fR, \fB\-\-mega\fR
Display the amount of memory in megabytes.
.TP
\fB\-g\fR, \fB\-\-giga\fR
Display the amount of memory in gigabytes.
.TP
\fB\-t\fR, \fB\-\-tera\fR
Display the amount of memory in terabytes.
.TP
\fB\-h\fR, \fB\-\-human\fR
Display the amount of memory in human readable format.
.TP
\fB\-V\fR, \fB\-\-version\fR
Prints version.
.TP
\fB\-\-help\fR
Prints help message.
.SH INTERACTIVE COMMANDS
.LP
The following commands are supported while in memwatch:
.LP
.TP
.B q
Exit memwatch.
.TP
.B b
Display the amount of memory in bytes.
.TP
.B k
Display the amount of memory in kilobytes.
.TP
.B m
Display the amount of memory in megabytes.
.TP
.B g
Display the amount of memory in gigabytes.
.TP
.B t
Display the amount of memory in terabytes.
.TP
.B h
Display the amount of memory in human readable format.
.TP
.B S
Toggle power size (1000 or 1024).
.SH AUTHOR
Pavel Balaev (pascal@unixdev.ru)
